Aincm3 = Aincm1;    Aincm1 = Ainc;
Hincm3 = Hincm1;    dAzdym3 = dAzdym1;
Aincm1(1) = floor(heaviside(n))*Ao*sin(omega*(t-dt/2))*ceil(heaviside(-(n-Nt)));
dAzdym1 = (Aincm1(2:Ninc+1)-Aincm1(1:Ninc))/dy;
Hincm1 = 1./(1/dt+sigHinc/(2*e0)).*(-(-Hincm3)/dt - sigHinc/e0.*Hincm3/2 + 1/u0*(dAzdym1-dAzdym3)/dt);
Ainc(2:Ninc) = 1./(e0/dt^2+sigEinc(2:Ninc)/(2*dt)).*(-e0*(-2*Aincm1(2:Ninc)+Aincm3(2:Ninc))/dt^2 - sigEinc(2:Ninc).*(-Aincm3(2:Ninc))/(2*dt) ...
               + (Hincm1(2:Ninc)-Hincm1(1:Ninc-1))/dy);

Axm7 = Axm5;    Axm5 = Axm3;    Axm3 = Axm1;    Axm1 = Ax;
Aym7 = Aym5;    Aym5 = Aym3;    Aym3 = Aym1;    Aym1 = Ay;
Azm7 = Azm5;    Azm5 = Azm3;    Azm3 = Azm1;    Azm1 = Az;
dHzdym5 = dHzdym3;  dHzdym3 = dHzdym1;  dHydzm5 = dHydzm3;  dHydzm3 = dHydzm1;
dHxdzm5 = dHxdzm3;  dHxdzm3 = dHxdzm1;  dHzdxm5 = dHzdxm3;  dHzdxm3 = dHzdxm1;
dHydxm5 = dHydxm3;  dHydxm3 = dHydxm1;  dHxdym5 = dHxdym3;  dHxdym3 = dHxdym1;
gradfxm5 = gradfxm3;    gradfxm3 = gradfxm1;    phisxm1 = phisxm0;  phisxm0 = phisx;
gradfym5 = gradfym3;    gradfym3 = gradfym1;    phisym1 = phisym0;  phisym0 = phisy;
gradfzm5 = gradfzm3;    gradfzm3 = gradfzm1;    phiszm1 = phiszm0;  phiszm0 = phisz;

phim0 = phisxm0 + phisym0 + phiszm0;
gradphix = 1./(1+sigxEx./(2*epEx)*dt).*(-sigxEx./epEx.*sumgradphix*dt + (phim0(2:Nx+1,:,:)-phim0(1:Nx,:,:))/dx);
gradphiy = 1./(1+sigyEy./(2*epEy)*dt).*(-sigyEy./epEy.*sumgradphiy*dt + (phim0(:,2:Ny+1,:)-phim0(:,1:Ny,:))/dy);
gradphiz = 1./(1+sigzEz./(2*epEz)*dt).*(-sigzEz./epEz.*sumgradphiz*dt + (phim0(:,:,2:Nz+1)-phim0(:,:,1:Nz))/dz);
sumgradphix = sumgradphix + gradphix;   sumgradphiy = sumgradphiy + gradphiy;   sumgradphiz = sumgradphiz + gradphiz;
phisx(2:Nx,2:Ny,2:Nz) = 1./(ep(2:Nx,2:Ny,2:Nz).^2.*mu(2:Nx,2:Ny,2:Nz)/dt^2+sigx(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).*mu(2:Nx,2:Ny,2:Nz)/(2*dt))...
                        .*(-ep(2:Nx,2:Ny,2:Nz).^2.*mu(2:Nx,2:Ny,2:Nz).*(-2*phisxm0(2:Nx,2:Ny,2:Nz)+phisxm1(2:Nx,2:Ny,2:Nz))/dt^2 ...
                        - sigx(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).*mu(2:Nx,2:Ny,2:Nz).*(-phisxm1(2:Nx,2:Ny,2:Nz))/(2*dt) ...
                        + (epEx(2:Nx,2:Ny,2:Nz).*gradphix(2:Nx,2:Ny,2:Nz)-epEx(1:Nx-1,2:Ny,2:Nz).*gradphix(1:Nx-1,2:Ny,2:Nz))/dx);
phisy(2:Nx,2:Ny,2:Nz) = 1./(ep(2:Nx,2:Ny,2:Nz).^2.*mu(2:Nx,2:Ny,2:Nz)/dt^2+sigy(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).*mu(2:Nx,2:Ny,2:Nz)/(2*dt))...
                        .*(-ep(2:Nx,2:Ny,2:Nz).^2.*mu(2:Nx,2:Ny,2:Nz).*(-2*phisym0(2:Nx,2:Ny,2:Nz)+phisym1(2:Nx,2:Ny,2:Nz))/dt^2 ...
                        - sigy(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).*mu(2:Nx,2:Ny,2:Nz).*(-phisym1(2:Nx,2:Ny,2:Nz))/(2*dt) ...
                        + (epEy(2:Nx,2:Ny,2:Nz).*gradphiy(2:Nx,2:Ny,2:Nz)-epEy(2:Nx,1:Ny-1,2:Nz).*gradphiy(2:Nx,1:Ny-1,2:Nz))/dy);
phisz(2:Nx,2:Ny,2:Nz) = 1./(ep(2:Nx,2:Ny,2:Nz).^2.*mu(2:Nx,2:Ny,2:Nz)/dt^2+sigz(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).*mu(2:Nx,2:Ny,2:Nz)/(2*dt))...
                        .*(-ep(2:Nx,2:Ny,2:Nz).^2.*mu(2:Nx,2:Ny,2:Nz).*(-2*phiszm0(2:Nx,2:Ny,2:Nz)+phiszm1(2:Nx,2:Ny,2:Nz))/dt^2 ...
                        - sigz(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).*mu(2:Nx,2:Ny,2:Nz).*(-phiszm1(2:Nx,2:Ny,2:Nz))/(2*dt) ...
                        + (epEz(2:Nx,2:Ny,2:Nz).*gradphiz(2:Nx,2:Ny,2:Nz)-epEz(2:Nx,2:Ny,1:Nz-1).*gradphiz(2:Nx,2:Ny,1:Nz-1))/dz);
phisx(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend) = phisx(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend) ...
                                             + dt^2./(ep(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend).^2.*mu(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend)).*rho;
Hsxz = 1./(muz+sigxHz.*muz./(2*epHz)*dt).*((Ay(2:Nx+1,1:Ny,1:Nz+1)-Ay(1:Nx,1:Ny,1:Nz+1))/dx - sigxHz.*muz./epHz.*sumHsxz*dt);
Hsxy = 1./(muy+sigxHy.*muy./(2*epHy)*dt).*(-(Az(2:Nx+1,1:Ny+1,1:Nz)-Az(1:Nx,1:Ny+1,1:Nz))/dx - sigxHy.*muy./epHy.*sumHsxy*dt);
Hsyx = 1./(mux+sigyHx.*mux./(2*epHx)*dt).*((Az(1:Nx+1,2:Ny+1,1:Nz)-Az(1:Nx+1,1:Ny,1:Nz))/dy - sigyHx.*mux./epHx.*sumHsyx*dt);
Hsyz = 1./(muz+sigyHz.*muz./(2*epHz)*dt).*(-(Ax(1:Nx,2:Ny+1,1:Nz+1)-Ax(1:Nx,1:Ny,1:Nz+1))/dy - sigyHz.*muz./epHz.*sumHsyz*dt);
Hszy = 1./(muy+sigzHy.*muy./(2*epHy)*dt).*((Ax(1:Nx,1:Ny+1,2:Nz+1)-Ax(1:Nx,1:Ny+1,1:Nz))/dz - sigzHy.*muy./epHy.*sumHszy*dt);
Hszx = 1./(mux+sigzHx.*mux./(2*epHx)*dt).*(-(Ay(1:Nx+1,1:Ny,2:Nz+1)-Ay(1:Nx+1,1:Ny,1:Nz))/dz - sigzHx.*mux./epHx.*sumHszx*dt);

tempincm1(1,:,:) = Aincm1(2:Ninc-Np)'*ones(1,length(Np+1:Nz-Np));
Hsxy(Np+1,Np+2:Ny-Np,Np+1:Nz-Np) = Hsxy(Np+1,Np+2:Ny-Np,Np+1:Nz-Np) + 1./(muy(Np+1,Np+2:Ny-Np,Np+1:Nz-Np)).*tempincm1/dx; % Back
Hsxy(Nx-Np,Np+2:Ny-Np,Np+1:Nz-Np) = Hsxy(Nx-Np,Np+2:Ny-Np,Np+1:Nz-Np) - 1./(muy(Nx-Np,Np+2:Ny-Np,Np+1:Nz-Np)).*tempincm1/dx; % Front
Hsyx(Np+2:Nx-Np,Np+1,Np+1:Nz-Np) = Hsyx(Np+2:Nx-Np,Np+1,Np+1:Nz-Np) - 1./(mux(Np+2:Nx-Np,Np+1,Np+1:Nz-Np))...
                                   .*ones(length(Np+2:Nx-Np),1,length(Np+1:Nz-Np))*Aincm1(2)/dy; % Left
Hsyx(Np+2:Nx-Np,Ny-Np,Np+1:Nz-Np) = Hsyx(Np+2:Nx-Np,Ny-Np,Np+1:Nz-Np) + 1./(mux(Np+2:Nx-Np,Np+1,Np+1:Nz-Np))...
                                    .*ones(length(Np+2:Nx-Np),1,length(Np+1:Nz-Np))*Aincm1(Ninc-Np)/dy; % Right
sumHsxz = sumHsxz + Hsxz; sumHsxy = sumHsxy + Hsxy; sumHsyx = sumHsyx + Hsyx; sumHsyz = sumHsyz + Hsyz; sumHszy = sumHszy + Hszy; sumHszx = sumHszx + Hszx;
Hx = Hsyx + Hszx;   Hy = Hsxy + Hszy;   Hz = Hsxz + Hsyz;    
dHzdym1(:,2:Ny,2:Nz) = (Hz(1:Nx,2:Ny,2:Nz)-Hz(1:Nx,1:Ny-1,2:Nz))/dy;  dHydzm1(:,2:Ny,2:Nz) = (Hy(1:Nx,2:Ny,2:Nz)-Hy(1:Nx,2:Ny,1:Nz-1))/dz;
dHxdzm1(2:Nx,:,2:Nz) = (Hx(2:Nx,1:Ny,2:Nz)-Hx(2:Nx,1:Ny,1:Nz-1))/dz;  dHzdxm1(2:Nx,:,2:Nz) = (Hz(2:Nx,1:Ny,2:Nz)-Hz(1:Nx-1,1:Ny,2:Nz))/dx;
dHydxm1(2:Nx,2:Ny,:) = (Hy(2:Nx,2:Ny,1:Nz)-Hy(1:Nx-1,2:Ny,1:Nz))/dx;  dHxdym1(2:Nx,2:Ny,:) = (Hx(2:Nx,2:Ny,1:Nz)-Hx(2:Nx,1:Ny-1,1:Nz))/dy;

dHxdzm1(Np+2:Nx-Np,Np+2:Ny-Np-1,Np+1) = dHxdzm1(Np+2:Nx-Np,Np+2:Ny-Np-1,Np+1) - ones(length(Np+2:Nx-Np),1)*Hincm1(2:Ninc-Np-1)/dz; % Bottom
dHxdzm1(Np+2:Nx-Np,Np+2:Ny-Np-1,Nz-Np+1) = dHxdzm1(Np+2:Nx-Np,Np+2:Ny-Np-1,Nz-Np+1) + ones(length(Np+2:Nx-Np),1)*Hincm1(2:Ninc-Np-1)/dz; % Top
dHxdym1(Np+2:Nx-Np,Np+2,Np+1:Nz-Np) = dHxdym1(Np+2:Nx-Np,Np+2,Np+1:Nz-Np) - ones(length(Np+2:Nx-Np),1,length(Np+1:Nz-Np))*Hincm1(1)/dy; % Left
dHxdym1(Np+2:Nx-Np,Ny-Np,Np+1:Nz-Np) = dHxdym1(Np+2:Nx-Np,Ny-Np,Np+1:Nz-Np) + ones(length(Np+2:Nx-Np),1,length(Np+1:Nz-Np))*Hincm1(Ninc-Np)/dy; % Right

fsx(2:Nx,2:Ny,2:Nz) = 1./(1+sigx(2:Nx,2:Ny,2:Nz)./(2*ep(2:Nx,2:Ny,2:Nz))*dt).*(-sigx(2:Nx,2:Ny,2:Nz)./ep(2:Nx,2:Ny,2:Nz).*sumfsx(2:Nx,2:Ny,2:Nz)*dt ...
              + 1./(mu(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).^2).*(epEx(2:Nx,2:Ny,2:Nz).*Ax(2:Nx,2:Ny,2:Nz)-epEx(1:Nx-1,2:Ny,2:Nz).*Ax(1:Nx-1,2:Ny,2:Nz))/dx);
fsy(2:Nx,2:Ny,2:Nz) = 1./(1+sigy(2:Nx,2:Ny,2:Nz)./(2*ep(2:Nx,2:Ny,2:Nz))*dt).*(-sigy(2:Nx,2:Ny,2:Nz)./ep(2:Nx,2:Ny,2:Nz).*sumfsy(2:Nx,2:Ny,2:Nz)*dt ...
              + 1./(mu(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).^2).*(epEy(2:Nx,2:Ny,2:Nz).*Ay(2:Nx,2:Ny,2:Nz)-epEy(2:Nx,1:Ny-1,2:Nz).*Ay(2:Nx,1:Ny-1,2:Nz))/dy);
fsz(2:Nx,2:Ny,2:Nz) = 1./(1+sigz(2:Nx,2:Ny,2:Nz)./(2*ep(2:Nx,2:Ny,2:Nz))*dt).*(-sigz(2:Nx,2:Ny,2:Nz)./ep(2:Nx,2:Ny,2:Nz).*sumfsz(2:Nx,2:Ny,2:Nz)*dt ...
              + 1./(mu(2:Nx,2:Ny,2:Nz).*ep(2:Nx,2:Ny,2:Nz).^2).*(epEz(2:Nx,2:Ny,2:Nz).*Az(2:Nx,2:Ny,2:Nz)-epEz(2:Nx,2:Ny,1:Nz-1).*Az(2:Nx,2:Ny,1:Nz-1))/dz);

fsz(Np+2:Nx-Np,Np+2:Ny-Np,Np+1) = fsz(Np+2:Nx-Np,Np+2:Ny-Np,Np+1) - 1./(mu(Np+2:Nx-Np,Np+2:Ny-Np,Np+1).*ep(Np+2:Nx-Np,Np+2:Ny-Np,Np+1).^2)...
                                  .*epEz(Np+2:Nx-Np,Np+2:Ny-Np,Np).*(ones(length(Np+2:Nx-Np),1)*Aincm1(2:Ninc-Np)/dz); % Bottom
fsz(Np+2:Nx-Np,Np+2:Ny-Np,Nz-Np+1) = fsz(Np+2:Nx-Np,Np+2:Ny-Np,Nz-Np+1) + 1./(mu(Np+2:Nx-Np,Np+2:Ny-Np,Nz-Np+1).*ep(Np+2:Nx-Np,Np+2:Ny-Np,Nz-Np+1).^2)...
                                     .*epEz(Np+2:Nx-Np,Np+2:Ny-Np,Nz-Np+1).*(ones(length(Np+2:Nx-Np),1)*Aincm1(2:Ninc-Np)/dz); % Top

sumfsx = sumfsx + fsx;  sumfsy = sumfsy + fsy;  sumfsz = sumfsz + fsz;  f = fsx + fsy + fsz;
gradfxm1(:,2:Ny,2:Nz) = 1./(1+sigxEx(:,2:Ny,2:Nz)./(2*epEx(:,2:Ny,2:Nz))*dt).*((f(2:Nx+1,2:Ny,2:Nz)-f(1:Nx,2:Ny,2:Nz))/dx ...
                        - sigxEx(:,2:Ny,2:Nz)./epEx(:,2:Ny,2:Nz).*sumgradfx(:,2:Ny,2:Nz)*dt);
gradfym1(2:Nx,:,2:Nz) = 1./(1+sigyEy(2:Nx,:,2:Nz)./(2*epEy(2:Nx,:,2:Nz))*dt).*((f(2:Nx,2:Ny+1,2:Nz)-f(2:Nx,1:Ny,2:Nz))/dy ...
                        - sigyEy(2:Nx,:,2:Nz)./epEy(2:Nx,:,2:Nz).*sumgradfy(2:Nx,:,2:Nz)*dt);
gradfzm1(2:Nx,2:Ny,:) = 1./(1+sigzEz(2:Nx,2:Ny,:)./(2*epEz(2:Nx,2:Ny,:))*dt).*((f(2:Nx,2:Ny,2:Nz+1)-f(2:Nx,2:Ny,1:Nz))/dz ...
                        - sigzEz(2:Nx,2:Ny,:)./epEz(2:Nx,2:Ny,:).*sumgradfz(2:Nx,2:Ny,:)*dt);
sumgradfx = sumgradfx + gradfxm1;   sumgradfy = sumgradfy + gradfym1;   sumgradfz = sumgradfz + gradfzm1;
Ax = 1./(epEx/dt^4+(sigyEx+sigzEx)/(2*dt^3)).*(-(dHzdym1-2*dHzdym3+dHzdym5)/dt^2 - sigzEx./epEx.*(dHzdym1-dHzdym5)/(2*dt) ...
     + (dHydzm1-2*dHydzm3+dHydzm5)/dt^2 + sigyEx./epEx.*(dHydzm1-dHydzm5)/(2*dt) - epEx.*(-4*Axm1+6*Axm3-4*Axm5+Axm7)/dt^4 ...
     - (sigyEx+sigzEx).*(-Axm1+Axm5-.5*Axm7)/dt^3 - sigyEx.*sigzEx./epEx.*(Axm1-2*Axm3+Axm5)/dt^2 + epEx.*(gradfxm1-2*gradfxm3+gradfxm5)/dt^2 ...
     + (sigyEx+sigzEx).*(gradfxm1-gradfxm5)/(2*dt) + sigyEx.*sigzEx./epEx.*gradfxm3);
Ax(Nxstart:Nxend-1,Nystart:Nyend,Nzstart:Nzend) = Ax(Nxstart:Nxend-1,Nystart:Nyend,Nzstart:Nzend) ...
                                                  + 1./(epEx(Nxstart:Nxend-1,Nystart:Nyend,Nzstart:Nzend)/dt^4).*(Jqxm1-2*Jqxm3+Jqxm5)/dt^2;
Ay = 1./(epEy/dt^4+(sigzEy+sigxEy)/(2*dt^3)).*(-(dHxdzm1-2*dHxdzm3+dHxdzm5)/dt^2 - sigxEy./epEy.*(dHxdzm1-dHxdzm5)/(2*dt) ...
     + (dHzdxm1-2*dHzdxm3+dHzdxm5)/dt^2 + sigzEy./epEy.*(dHzdxm1-dHzdxm5)/(2*dt) - epEy.*(-4*Aym1+6*Aym3-4*Aym5+Aym7)/dt^4 ...
     - (sigzEy+sigxEy).*(-Aym1+Aym5-.5*Aym7)/dt^3 - sigzEy.*sigxEy./epEy.*(Aym1-2*Aym3+Aym5)/dt^2 + epEy.*(gradfym1-2*gradfym3+gradfym5)/dt^2 ...
     + (sigzEy+sigxEy).*(gradfym1-gradfym5)/(2*dt) + sigzEy.*sigxEy./epEy.*gradfym3);
Ay(Nxstart:Nxend,Nystart:Nyend-1,Nzstart:Nzend) = Ay(Nxstart:Nxend,Nystart:Nyend-1,Nzstart:Nzend) ...
                                                  + 1./(epEy(Nxstart:Nxend,Nystart:Nyend-1,Nzstart:Nzend)/dt^4).*(Jqym1-2*Jqym3+Jqym5)/dt^2;
Az = 1./(epEz/dt^4+(sigxEz+sigyEz)/(2*dt^3)).*(-(dHydxm1-2*dHydxm3+dHydxm5)/dt^2 - sigyEz./epEz.*(dHydxm1-dHydxm5)/(2*dt) ...
     + (dHxdym1-2*dHxdym3+dHxdym5)/dt^2 + sigxEz./epEz.*(dHxdym1-dHxdym5)/(2*dt) - epEz.*(-4*Azm1+6*Azm3-4*Azm5+Azm7)/dt^4 ...
     - (sigxEz+sigyEz).*(-Azm1+Azm5-.5*Azm7)/dt^3 - sigxEz.*sigyEz./epEz.*(Azm1-2*Azm3+Azm5)/dt^2 + epEz.*(gradfzm1-2*gradfzm3+gradfzm5)/dt^2 ...
     + (sigxEz+sigyEz).*(gradfzm1-gradfzm5)/(2*dt) + sigxEz.*sigyEz./epEz.*gradfzm3);
Az(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend-1) = Az(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend-1) ...
                                                  + 1./(epEz(Nxstart:Nxend,Nystart:Nyend,Nzstart:Nzend-1)/dt^4).*(Jqzm1-2*Jqzm3+Jqzm5)/dt^2;